feat:添加一篇翻译
freeCodeCamp/news-translation pull request #256
Opened 2020-09-29 09:54 UTC by nsuedu

2020-09-29 10:08 UTC, TechQuery commented on chinese/articles/Learn the basics of the JavaScript module system and build your own library.md
> +> - 译者：古月
以上**元数据**也放到本 PR 的**楼主帖**里一份

2020-09-29 10:08 UTC, TechQuery commented on chinese/articles/Learn the basics of the JavaScript module system and build your own library.md
> +# 了解 JavaScript 模块系统的基础知识，并建立自己的库(译)🍜
**中文标题**作为本 PR 的标题

2020-09-29 10:30 UTC, TechQuery requested changes

2020-09-29 10:30 UTC, TechQuery commented on chinese/articles/Learn the basics of the JavaScript module system and build your own library.md
> +<br />身为“前端工程师“，我想很多人都听过说过“javascript 模块”。那你们每个人都知道如何处理它，以及它在日常工作中如何发挥作用吗？
用**空行**代替 `<br />`。

虽然 MarkDown 支持 HTML 标签，但我们优先使用 **MarkDown 语法**。

2020-09-29 10:30 UTC, TechQuery commented on chinese/articles/Learn the basics of the JavaScript module system and build your own library.md
> +<a name="hugA9"></a>
删掉无用标签

2020-09-29 10:30 UTC, TechQuery commented on chinese/articles/Learn the basics of the JavaScript module system and build your own library.md
> +![image.png](https://cdn.nlark.com/yuque/0/2020/png/382504/1601263710161-bb1c81cb-3fa3-4f0a-b652-2e891a801c48.png#align=left&display=inline&height=441&margin=%5Bobject%20Object%5D&name=image.png&orig
1. 清理**嵌套**的加粗符号
2. 含**中文内容**的短句，外面要用中文括号

2020-09-29 10:30 UTC, TechQuery commented on chinese/articles/Learn the basics of the JavaScript module system and build your own library.md
> +1. 应该发布哪些文件？
理顺**项目列表号**

2020-09-29 10:30 UTC, TechQuery commented on chinese/articles/Learn the basics of the JavaScript module system and build your own library.md
> +# JS 模块系统到底是什么呢？
一篇文章的一级标题全局唯一，请根据**文章结构**依次理顺下级标题

2020-09-29 10:30 UTC, TechQuery commented on chinese/articles/Learn the basics of the JavaScript module system and build your own library.md
> +<br />身为“前端工程师“，我想很多人都听过说过“javascript 模块”。那你们每个人都知道如何处理它，以及它在日常工作中如何发挥作用吗？
拼写规范：JavaScript

2020-09-29 10:30 UTC, TechQuery commented on chinese/articles/Learn the basics of the JavaScript module system and build your own library.md
> +<br />问题是，每当更改一部分代码时，我都需要在所有项目中手动同步这些更改。 为了避免所有这些繁琐的手动任务，我决定**提取通用功能并从中组成一个 npm 软件包**。 这样，团队中的其他人将能够将它们重新用作依赖项，并在每次推出新版本时都可以对其进行更新。<br />
拼写规范：NPM

2020-09-29 10:30 UTC, TechQuery commented on chinese/articles/Learn the basics of the JavaScript module system and build your own library.md
> +- 所有应用程序保持同步。 无论何时进行更改，所有应用程序仅需要运行“ npm update”命令。
行内命令要用 **MarkDown 规范语法**：

```MarkDown
`npm update`
```
并在代码块两边空格。

2020-09-29 10:30 UTC, TechQuery commented on chinese/articles/Learn the basics of the JavaScript module system and build your own library.md
> +1. 应该针对哪些 JS 模块系统（commonjs, amd, harmony）。
拼写规范：CommonJS、AMD、ES modules

2020-09-29 10:30 UTC, TechQuery commented on chinese/articles/Learn the basics of the JavaScript module system and build your own library.md
> +- 由**node.js**实现。
拼写规范：Node.js

2020-09-29 10:30 UTC, TechQuery commented on chinese/articles/Learn the basics of the JavaScript module system and build your own library.md
> +- 通过**“ \*\***module.exports\***\*”**导出模块
1. 清理**嵌套**的加粗符号
2. 使用 MarkDown **行内代码**语法

2020-09-29 10:30 UTC, TechQuery commented on chinese/articles/Learn the basics of the JavaScript module system and build your own library.md
> +- 由**RequireJs**实现
1. 拼写规范：RequireJS
2. **中英文、数字之间加空格**

2020-09-29 10:30 UTC, TechQuery commented on chinese/articles/Learn the basics of the JavaScript module system and build your own library.md
> +- 当你在**客户端（浏览器）环境**中**，**异步加载模块时使用
清理不必要的加粗符号

2020-09-29 10:30 UTC, TechQuery commented on chinese/articles/Learn the basics of the JavaScript module system and build your own library.md
> +Webpack, Rollup, Babel。 这些我们在日常工作中使用的工具，用于承载我们的应用程序/库/软件包。 没有它们，我无法想象现代的 Web 开发有多么糟糕。 因此，我们无法将它们进行比较 ❌<br />
webpack 官方规定名字全小写

2020-09-29 10:30 UTC, TechQuery commented on chinese/articles/Learn the basics of the JavaScript module system and build your own library.md
> +<br />**我的建议：对库使用 RollupJS，对应用程序使用 Webpack。**
官方命名：Rollup.js

2020-09-29 10:30 UTC, TechQuery commented on chinese/articles/Learn the basics of the JavaScript module system and build your own library.md
> +```
修正代码块语言名、语法

2020-09-29 10:30 UTC, TechQuery commented on chinese/articles/Learn the basics of the JavaScript module system and build your own library.md
> +importimport {Button} from "uilibrary";
错误换行

2020-09-29 12:41 UTC, TechQuery requested changes

2020-09-29 12:41 UTC, TechQuery commented on chinese/articles/Learn the basics of the JavaScript module system and build your own library.md
> +![image.png](https://cdn.nlark.com/yuque/0/2020/png/382504/1601263710161-bb1c81cb-3fa3-4f0a-b652-2e891a801c48.png#align=left&display=inline&height=441&margin=%5Bobject%20Object%5D&name=image.png&orig
图片后面的都是图片说明吗？如果是，请用以下结构：

```HTML
<figure>
    <img src="path/to/image" />
    <figcaption>图片说明</figcaption>
</figure>
```
参考：https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/figure

2020-09-29 12:41 UTC, TechQuery commented on chinese/articles/Learn the basics of the JavaScript module system and build your own library.md
> +2. 应该针对哪些 JS 模块系统（CommonJS, AMD, ES modules）。
中文内容中的**列举项**应用**顿号**

2020-09-29 12:41 UTC, TechQuery commented on chinese/articles/Learn the basics of the JavaScript module system and build your own library.md
> +4. Should I bundle the source?-应该打包源码吗？
保留原文的意思是心里没底？我的建议：

- 第 3 条：我需要转译源码吗？
- 第 4 条：我需要打包源码吗？

2020-09-29 12:41 UTC, TechQuery commented on chinese/articles/Learn the basics of the JavaScript module system and build your own library.md
>  - When you import you get back an object(导入时，您将获得一个对象)
> 当你导入时，你会获得一个对象

2020-09-29 12:41 UTC, TechQuery commented on chinese/articles/Learn the basics of the JavaScript module system and build your own library.md
>  - No static analyzing, as you get an object, so property lookup is at runtime(当您获得对象时，无需进行静态分析，因此属性查找在运行时进行)
> 因为你得到的是一个对象，所以属性查找在运行时进行，无法静态分析

2020-09-29 12:41 UTC, TechQuery commented on chinese/articles/Learn the basics of the JavaScript module system and build your own library.md
>  > _tree shaking_ 是一个术语，通常用于描述移除 JavaScript 上下文中的未引用代码(dead-code)。它依赖于 ES2015 模块系统中的[静态结构特性](http://exploringjs.com/es6/ch_modules.html#static-module-structure)，例如 [`import`](https://developer.mozilla
将被文本包围的链接替换为[标签链接](https://daringfireball.net/projects/markdown/syntax#link)：

```MarkDown
xxx[yyy][1]zzz

[1]: https://test.com
```

2020-09-29 12:41 UTC, TechQuery commented on chinese/articles/Learn the basics of the JavaScript module system and build your own library.md
>  )
HTML 标签外没有圆括号……

2020-09-29 12:41 UTC, TechQuery commented on chinese/articles/Learn the basics of the JavaScript module system and build your own library.md
> +\*\* 现在，如果我们只是简单地将 src 转换为 lib 并将该 lib 托管在 CDN 上，那么我们的使用者实际上可以得到他们想要的任何东西而没有任何开销。 “代码更少，加载更快”。 ✅
删除类似本行开头这样的意外转义的符号

2020-09-29 12:46 UTC, TechQuery commented
如果你用 VS Code，装上 [Prettier 扩展](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode)格式化一下，然后再用 NPM 装 [ZhLint](https://github.com/Jinjiang/zhlint) 检查一下。

2020-09-29 14:06 UTC, TechQuery commented on chinese/articles/Learn the basics of the JavaScript module system and build your own library.md
> +\*\* 现在，如果我们只是简单地将 src 转换为 lib 并将该 lib 托管在 CDN 上，那么我们的使用者实际上可以得到他们想要的任何东西而没有任何开销。 “代码更少，加载更快”。 ✅
我说的是“意外”转义的“符号”，不是“所有星号”……

比如 `\*\*` 很可能是 HTML to MarkDown 解析器找不到匹配的加粗双星号，为了保留它而用 `\` 转义以保安全，这些都需要你根据上下文自己清理，而不是统统换成反引号，只有代码块才用反引号……

2020-09-29 15:32 UTC, nsuedu reviewed
重新导出一份 Markdown文件进行修改

2020-09-29 15:33 UTC, nsuedu commented on chinese/articles/Learn the basics of the JavaScript module system and build your own library.md
> +\*\* 现在，如果我们只是简单地将 src 转换为 lib 并将该 lib 托管在 CDN 上，那么我们的使用者实际上可以得到他们想要的任何东西而没有任何开销。 “代码更少，加载更快”。 ✅
重新导出一份Markdown文件进行修改

2020-09-29 15:42 UTC, TechQuery commented
> 重新导出一份 Markdown文件进行修改

```Shell
git clone https://github.com/nsuedu/news-translation
```

2020-09-30 03:55 UTC, merged

2020-09-30 05:14 UTC, TechQuery commented
@nsuedu 仔细看一下 05de8b3 我每一处修改，对你以后翻译文章有好处

还有几个保留较长原文的句子，你确定不翻译完？