feat:JavaScript 字符串反转的三种方式
freeCodeCamp/news-translation pull request #271
Opened 2020-12-04 08:56 UTC by nsuedu

> -   原文地址：[Three Ways to Reverse a String in JavaScript JavaScript 字符串反转的三种方式](https://www.freecodecamp.org/news/how-to-reverse-a-string-in-javascript-in-3-different-ways-75e4763c68cb/)
> -   原文作者：Sonya Moisset
> -   译者：@nsuedu
> -   校对者：

2020-12-04 09:19 UTC, TechQuery approved these changes

2020-12-08 12:25 UTC, TechQuery commented
@nsuedu 怎么出现了多篇文章？

2020-12-08 13:32 UTC, nsuedu reviewed
> @nsuedu 怎么出现了多篇文章？

因为你们没得及关闭这个 PR， 而我有多翻译了 

> @nsuedu 怎么出现了多篇文章？

你们没有来得及关闭 PR， 而我多翻译了几篇并且 push 了😂

2020-12-08 13:46 UTC, nsuedu reviewed
> @nsuedu 怎么出现了多篇文章？

因为你们没得及关闭这个 PR， 而我有多翻译了 

> @nsuedu 怎么出现了多篇文章？

你们没有来得及关闭 PR， 而我多翻译了几篇并且 push 了😂

2020-12-08 18:21 UTC, TechQuery commented
@nsuedu 每一篇翻译都要**新开分支**，PR 也会相应新开，与之前的 PR 是否很快合并无关。

请将后面几篇从该分支删除，并分别放在单独的分支里创建 PR。

2020-12-09 07:18 UTC, nsuedu commented
> @nsuedu 每一篇翻译都要**新开分支**，PR 也会相应新开，与之前的 PR 是否很快合并无关。
> 
> 请将后面几篇从该分支删除，并分别放在单独的分支里创建 PR。

OK！

2020-12-09 08:17 UTC, TechQuery requested changes

2020-12-09 08:17 UTC, TechQuery commented on chinese/articles/how-to-reverse-a-string-in-javascript-in-3-different-ways.md
>  5th call – reverseString("o")       will return   reverseString("")               + "o"
非代码部分可以翻译一下

2020-12-09 08:17 UTC, TechQuery commented on chinese/articles/how-to-reverse-a-string-in-javascript-in-3-different-ways.md
>  -   [charAt() method — MDN][17]
非代码、非缩写部分都可翻译一下

2020-12-10 13:41 UTC, TechQuery approved these changes

2020-12-10 13:42 UTC, merged