Advanced TypeScript Types Cheat Sheet (with Examples) TS 高级类型清单(附 demo)🛵]
freeCodeCamp/news-translation pull request #278
Opened 2020-12-09 08:13 UTC by nsuedu

> -   原文地址：[Advanced TypeScript Types Cheat Sheet (with Examples) TS 高级类型清单(附 demo)🛵](https://www.freecodecamp.org/news/react-typescript-how-to-set-up-types-on-hooks/)
> -   原文作者：Ibrahima Ndaw
> -   译者：@nsuedu
> -   校对者：

2020-12-16 09:16 UTC, nsuedu commented
@TechQuery 水哥，有空就PR一下吧..🥲

2021-01-08 13:20 UTC, TechQuery requested changes

2021-01-08 13:20 UTC, TechQuery commented on chinese/articles/Advanced TypeScript Types Cheat Sheet (with Examples).md
> +> -   原文地址：[Advanced TypeScript Types Cheat Sheet (with Examples) TS 高级类型清单(附 demo)🛵](https://www.freecodecamp.org/news/react-typescript-how-to-set-up-types-on-hooks/)
这篇的原文呢？

2021-01-08 13:20 UTC, TechQuery commented on chinese/articles/how-to-reverse-a-string-in-javascript-in-3-different-ways.md
> +> -   原文地址：[Three Ways to Reverse a String in JavaScript JavaScript 字符串反转的三种方式](https://www.freecodecamp.org/news/how-to-reverse-a-string-in-javascript-in-3-different-ways-75e4763c68cb/)
这篇翻译应从**独立分支**发 PR，不要混在这个 PR 里

2021-02-03 09:50 UTC, nsuedu commented on chinese/articles/Advanced TypeScript Types Cheat Sheet (with Examples).md
> +> -   原文地址：[Advanced TypeScript Types Cheat Sheet (with Examples) TS 高级类型清单(附 demo)🛵](https://www.freecodecamp.org/news/react-typescript-how-to-set-up-types-on-hooks/)
@TechQuery  fixed

2021-02-03 09:50 UTC, nsuedu commented on chinese/articles/how-to-reverse-a-string-in-javascript-in-3-different-ways.md
> +> -   原文地址：[Three Ways to Reverse a String in JavaScript JavaScript 字符串反转的三种方式](https://www.freecodecamp.org/news/how-to-reverse-a-string-in-javascript-in-3-different-ways-75e4763c68cb/)
> 这篇翻译应从**独立分支**发 PR，不要混在这个 PR 里

fixed

2021-02-04 14:41 UTC, TechQuery commented on chinese/articles/Advanced TypeScript Types Cheat Sheet (with Examples).md
> +> -   原文地址：[Advanced TypeScript Types Cheat Sheet (with Examples) TS 高级类型清单(附 demo)🛵](https://www.freecodecamp.org/news/react-typescript-how-to-set-up-types-on-hooks/)
@nsuedu fix 了就点这下面的 `Resolve conversation` 按钮

2021-02-04 14:47 UTC, TechQuery commented
@nsuedu 方便的话，在本地格式化一下吧：
https://github.com/freeCodeCamp/news-translation#local

2021-02-05 02:59 UTC, nsuedu commented
> @nsuedu 方便的话，在本地格式化一下吧：
> https://github.com/freeCodeCamp/news-translation#local

`npm test `  提示没有改变任何文件，因此我执行了 `npm  run format` 

```
clj@cljdeMacBook-Pro news-translation % npm test     

> news-translation@1.0.0 test /Users/clj/works&life/my-code/GitHub/news-translation
> lint-staged

ℹ No staged files found.
```

2021-02-05 12:02 UTC, TechQuery approved these changes

2021-02-05 12:03 UTC, merged