在 JavaScript 中发起 HTTP 请求的常用方法
freeCodeCamp/news-translation pull request #296
Opened 2020-12-22 08:51 UTC by arronKler

#291

2021-01-18 14:35 UTC, miyaliu666 requested changes
谢谢 @arronKler 翻译这篇文章！整体比较流畅，我提了一点修改建议，供参考。

接下来，请把你的邮箱发给我，我邀请你注册成为 [freeCodeCamp 专栏](https://chinese.freecodecamp.org/news)作者。等你设置好作者信息（记得设置一个头像哦，最好是本人照片）之后，我们会以你的名义发布这篇译文。
除了发布译文，你还可以在专栏发布自己的原创文章。
欢迎阅读我们写给社区作者的[写作指南](https://chinese.freecodecamp.org/news/developer-news-style-guide/)。

此外，欢迎你参加每周六下午的在线技术翻译工作坊（详见本仓库 readme）。

2021-01-18 14:35 UTC, miyaliu666 commented on chinese/articles/here-is-the-most-popular-ways-to-make-an-http-request-in-javascript.md
> +要在 Ajax 中发起一个 HTTP 调用，你需要先用 `XMLHttpRequest()` 创建一个新的对象，准备好 URL 和 HTTP 方法（此处为 GET）。最后，使用 `open()` 方法将两者结合起来，并调用 `send()` 方法执行请求。
你需要初始化一个新的 `XMLHttpRequest()` 方法，指定 URL 端点和 HTTP 方法（在本例中为 GET）。

2021-01-18 14:35 UTC, miyaliu666 commented on chinese/articles/here-is-the-most-popular-ways-to-make-an-http-request-in-javascript.md
> +`axios` 需要一个必填参数，当然你也可以提供第二个可选参数，用来传递一些简单的 query 数据。
`axios` 需要一个必填参数，当然你也可以提供第二个可选参数。这个示例调用一些数据作简单的查询。

2021-01-22 03:27 UTC, arronKler commented on chinese/articles/here-is-the-most-popular-ways-to-make-an-http-request-in-javascript.md
> +Javascript 拥有非常棒的建立 HTTP 请求并向服务端发送或者接收资源的模块和方法。本文会带着大家一起看看在 JavaScript 中常用的建立 HTTP 请求的方式有哪些。
嗯，这个更清晰简洁

2021-01-22 03:28 UTC, arronKler commented on chinese/articles/here-is-the-most-popular-ways-to-make-an-http-request-in-javascript.md
> +`axios` 需要一个必填参数，当然你也可以提供第二个可选参数，用来传递一些简单的 query 数据。
You are right!

2021-01-22 03:29 UTC, arronKler commented
我的邮箱是：panzer9@126.com

2021-01-22 12:47 UTC, miyaliu666 commented
谢谢回复。已经给你发送注册邀请了，请在邮箱查收。

![image](https://user-images.githubusercontent.com/19358186/105492235-98c7bd00-5cf2-11eb-9325-eef8f757a58c.png)

[译文](https://chinese.freecodecamp.org/news/the-most-popular-ways-to-make-an-http-request-in-javascript/)已经发布在 freeCodeCamp 中文专栏，等你注册好账户，我会把作者改成你😄

请你根据我的修改建议，在这里修改并作最后一次 commit，然后我会 merge。

明天下午 1 点 - 3 点，我们会在 [Skype 会议室](https://join.skype.com/WNwhdeBLA1RT)作译者交流，欢迎你加入啊（提前下载好 Skype app 哈）。有什么问题或建议都可以在明天的活动上提出。这次活动我们主要是讨论中文课程翻译、文章翻译中的问题，另外，计划协作汇总技术词汇表，供大家在翻译时参考。

2021-01-23 03:33 UTC, arronKler commented
完成

2021-01-25 13:27 UTC, merged