什么是 JavaScript 元编程
freeCodeCamp/news-translation pull request #297
Opened 2020-12-22 16:11 UTC by Humilitas

翻译完成，请校对。 #265

2021-01-04 04:33 UTC, miyaliu666 requested changes
谢谢 @Humilitas 翻译本文，我只有两个小建议，供参考 :D

2021-01-04 04:33 UTC, miyaliu666 commented on chinese/articles/what-is-metaprogramming-in-javascript-in-english-please.md
> +在 ES6 中，Reflect 是一个新的 `全局对象`（像 math 一样），它提供了一些工具函数，其中一些函数与 `Object` 或 `Function` 对象中的同名方法功能是相同的。
其中一些函数与 ES5 中全局对象的方法具有相同作用。

2021-01-04 04:33 UTC, miyaliu666 commented on chinese/articles/what-is-metaprogramming-in-javascript-in-english-please.md
> +这样，如果 `func` 不是 callable 对象，会抛出 [`TypeError`][2]。此外 `Reflect.apply()` 也更简洁、易于理解。
callable => 可调用

2021-01-05 03:48 UTC, Humilitas commented on chinese/articles/what-is-metaprogramming-in-javascript-in-english-please.md
> +在 ES6 中，Reflect 是一个新的 `全局对象`（像 math 一样），它提供了一些工具函数，其中一些函数与 `Object` 或 `Function` 对象中的同名方法功能是相同的。
这一段内容在原文中的表述为“In ES6, Reflect is a new Global Object (like Math) that provides a number of utility functions. Some of these functions may do exactly the same thing as the methods from Object or Function.  ”，我自行选择了原文中的表述来翻译。

2021-01-07 08:27 UTC, merged