完成翻译
freeCodeCamp/news-translation pull request #299
Opened 2020-12-24 06:06 UTC by pjwok

#249 完成翻译

2020-12-28 14:00 UTC, AmosChenYQ commented
@pjwok @miyaliu666 认领翻译

2020-12-28 14:51 UTC, miyaliu666 commented
@AmosChenYQ 好的，谢谢参与校对，已经 assign 给你啦：）

有什么问题，可以在[社区聊天室](https://chat.freecodecamp.org/channel/tongyong)联系我讨论。

2020-12-28 16:01 UTC, AmosChenYQ requested changes

2020-12-28 16:01 UTC, AmosChenYQ commented on chinese/articles/building-bots.md
> -<span class="token keyword" style="box-sizing: inherit; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: i
这些html是原文就有的还是啥情况...要不要留着... @miyaliu666

2020-12-30 05:04 UTC, pjwok commented on chinese/articles/building-bots.md
> -<span class="token keyword" style="box-sizing: inherit; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: i
我看过原文里面是python的代码和文章的内容，可能是转成文档的时候出现了编译错误混杂在一起了

2020-12-30 06:36 UTC, AmosChenYQ commented on chinese/articles/building-bots.md
> -<span class="token keyword" style="box-sizing: inherit; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: i
OK 那就不用留着了 😀

2021-01-04 03:39 UTC, miyaliu666 commented on chinese/articles/building-bots.md
> +Felix 和我在学习 **InstaPy** 库和他的 **Travian-Bot** 库的基础上创建了一个**教你如何创建自己的机器人**的在线视频。实际上，他也因为这个库太火爆导致想关闭这个项目。
“导致”二字可删掉

2021-01-04 03:41 UTC, miyaliu666 commented on chinese/articles/building-bots.md
> +通过理解登录和身份验证的逻辑，我们可以使用脚本来复制这一动作。然后即使他们不对外提供应用界面，我们也可以创建自己的接口脚本来使用他们的应用。
“他们自己” 的 “自己” 二字可以删掉

2021-01-04 04:02 UTC, miyaliu666 commented on chinese/articles/building-bots.md
> +在实际的程序中，基于 API 逆向工程的自动化程序更为常见。在下文的“自动化的道德考量”中也会探讨机器人冒名顶替真是人类的问题
在实际的机器人程序，以及在下文”自动化的道德考量“的光谱图里的”机器冒充人类“阶段，基于 API 逆向工程的自动化程序更为常见。

2021-01-04 04:08 UTC, miyaliu666 commented
谢谢 @pjwok 翻译本文，整体比较流畅！请结合校对建议修改译文，commit 终稿。

谢谢 @AmosChenYQ 校对，我在你的校对建议下面又添加了一些建议😄  也欢迎你参加我们每周六下午 1 点 - 3 点（北京时间）举办的技术翻译工作坊，感兴趣的话，请加入 [Skype 会议室](https://join.skype.com/WNwhdeBLA1RT)。

2022-05-17 12:18 UTC, merged