VS Code snippet 入门指南
freeCodeCamp/news-translation pull request #325
Opened 2021-01-14 07:52 UTC by CodeByZack

closes #311

2021-01-22 12:49 UTC, miyaliu666 commented
谢谢 @CodeByZack 翻译这篇文章！稍后我们会校对。

明天下午 1 点 - 3 点，我们会在 [Skype 会议室](https://join.skype.com/WNwhdeBLA1RT)作译者交流，欢迎你加入啊（需要提前下载好 Skype app）。有什么问题或建议都可以在明天的活动上提出。这次活动我们主要是讨论中文课程翻译、文章翻译中的问题，另外，计划协作汇总技术词汇表，供大家在翻译时参考。

2021-01-22 13:03 UTC, CodeByZack commented
呃呃，能力有限，让我自己先检查一次哈。检查完了你们再检查可以吧。

关于会议，明天要加班，可能参与不了哈。

2021-01-22 14:49 UTC, miyaliu666 commented
好的，你先检查，不着急😊
嗯嗯，会议每周都有，你有时间的时候随时可以参与。

2021-01-23 03:12 UTC, CodeByZack commented
大概检查了一次。感觉还是翻译的不太流畅，多多包含。

2021-03-02 13:13 UTC, tianheg commented on chinese/articles/definitive-guide-to-snippets-visual-studio-code.md
> +> -   译者：董凯
译者这里，根据 [贡献指南](https://github.com/freeCodeCamp/news-translation/blob/master/Contributing.md)：

在打开的**译文编辑器**开头“译者”处写上自己的 GitHub ID

2021-03-02 14:11 UTC, tianheg requested changes

2021-03-02 14:59 UTC, tianheg requested changes

2021-03-02 14:59 UTC, tianheg commented on chinese/articles/definitive-guide-to-snippets-visual-studio-code.md
> +现在大多数代码编辑器都支持了代码片段的功能。本文中我将使用如今最流行的代码编辑器 Visual Studio Code (VS Code) 来演示代码片段。
大多数代码编辑器支持代码片段这一开箱即用的功能。

2021-03-02 14:59 UTC, tianheg commented on chinese/articles/definitive-guide-to-snippets-visual-studio-code.md
> +接下来，让我们深入了解与代码片段的相关所有细节。
接下来，让我们深入了解与代码片段相关的所有细节。

2021-03-02 14:59 UTC, tianheg commented on chinese/articles/definitive-guide-to-snippets-visual-studio-code.md
> +> 一段代码片段就是通过输入命令或者触发文本向文档中插入的模板内容。
> 一个代码片段就是一个可被插入文档的模板。通过命令或一些触发文本插入代码片段。

2021-03-03 10:01 UTC, tianheg requested changes
Complete review

2022-10-13 02:37 UTC, miyaliu666 commented
这篇文章之前已经发布在[专栏](https://chinese.freecodecamp.org/news/definitive-guide-to-snippets-visual-studio-code/)，因为之前等着译者确认校对者的建议，所以忘记了合并。谢谢 @CodeByZack 翻译这篇文章，译文整体比较流畅，也谢谢 @tianheg 帮助校对，我刚才已经把你的建议添加到发布的译文中了。

请 @CodeByZack 联系小助手微信 fcczhongguo（或者直接在这里留言）把你的邮箱发给我，我邀请你注册成为 freeCodeCamp [专栏](https://chinese.freecodecamp.org/news/)作者。等你设置好信息之后，我会在把译文作者改成你。记得设置一个头像哦，最好是本人照片。

除了发布译文，你还可以在专栏发布自己的原创文章。发布文章的流程是：作者写好草稿，把链接发给我，我在 review 之后发布。

同时，欢迎你参与周日上午 10 点 - 11 点半（北京时间）的线上[贡献者交流会](https://forum.freecodecamp.org/t/freecodecamp/516584)，每两周组织一次，最近的一次是这周日。请联系小助手微信以获得交流会的会议室链接。

2022-10-13 02:37 UTC, merged

2022-10-13 05:42 UTC, CodeByZack commented
> fcczhongguo

邮箱是 958059970@qq.com

2022-10-14 07:22 UTC, CodeByZack commented
@miyaliu666
邮箱是 [958059970@qq.com](mailto:958059970@qq.com)