feat:Add news article crawler script ;增加news文章爬虫脚本
freeCodeCamp/news-translation pull request #389
Opened 2021-03-13 17:52 UTC by stevending1st

feat:Add news article crawler script 
There is currently a known bug. If there is a video in the news article, it will be ignored.
------
增加 news 文章爬虫脚本
(目前有一个已知 bug, news 文章中如果有视频，将被忽略)

2021-04-01 08:22 UTC, stevending1st commented
I updated the code, please review again. @QuincyLarson

2021-04-02 10:57 UTC, TechQuery commented
感觉这么大代码量可以独立成一个 action 仓库了😂

2021-04-02 11:23 UTC, stevending1st commented
> 感觉这么大代码量可以独立成一个 action 仓库了😂
> 建议在 @freeCodeCamp-China 建一个 `fetch-markdown-from-issue` 的代码库，本仓库 action 配置直接引用、传参。

我最近准备完成我的项目，不然我得在家一直呆下去，所以先用这个吧。
之前计划等写完项目，找到工作，写把这个封装成一个 npm 包，直接执行 `命令 URL` ，直接生成文章。
单独写一个 action 仓库的建议很好，可惜现在没有太多时间。

2021-04-03 11:56 UTC, TechQuery requested changes

2021-04-03 11:56 UTC, TechQuery commented on .github/workflows/WebPageToMarkdown.yml
> +                  fi;
这种有复杂逻辑的长脚本，建议放在**独立的 `.sh` 文件**中，YAML 配置文件只管**传参调用**，也方便 Shell 脚本**代码高亮**、**格式化**。

2021-04-03 11:56 UTC, TechQuery commented on .github/workflows/WebPageToMarkdown.yml
> +                  ref: ${{ github.head_ref }}
这个 action 默认 checkout 的就是 HEAD 吧？

2021-04-03 11:56 UTC, TechQuery commented on script/toMarkdown/LICENSE
> +Copyright (c) 2020 X-lab
这里应该写“freeCodeCamp”？ @miyaliu666 ，你了解 FCC 的贡献版权问题吗？

2021-04-03 11:56 UTC, TechQuery commented on script/toMarkdown/README-zh-cn.md
> +**项目结构**
可用 `####` 四级标题，后面以此类推

2021-04-03 11:56 UTC, TechQuery commented on script/toMarkdown/README-zh-cn.md
> +<hr />
可用 `---` MarkDown 分割线

2021-04-03 11:56 UTC, TechQuery commented on script/toMarkdown/toMarkdownSubfun.js
> +      resolve(fileName);
可以把这些逻辑写在上面的 `if` 子句中，不要留有空代码块；

而且 `resolve`、`reject` 都是函数，不是 `return`、`throw` 语句，不会中断后面代码的执行。

2021-04-03 11:56 UTC, TechQuery commented on script/toMarkdown/toMarkdownSubfun.js
> +      reject(Err_NoPath);
此处要 `return`（下同）

2021-04-03 11:56 UTC, TechQuery commented on script/toMarkdown/toMarkdownSubfun.js
> +    const authorName = $(".author-card-name").children("a").text();
可用 `.class > tag` 这样的**子元素选择符**来减少查找方法的调用，提高性能（下同）

2021-04-03 11:56 UTC, TechQuery commented on script/toMarkdown/toMarkdownSubfun.js
> +    const markdown = turndownService.turndown(article);
反复使用的**工具对象**放在**模块最顶级**初始化

2021-04-03 11:56 UTC, TechQuery commented on script/toMarkdown/toMarkdownSubfun.js
> +    })
`fs` 内置模块现在有[官方 Promise 版本](https://devdocs.io/node~14_lts/fs#fs_fspromises_writefile_file_data_options)

2021-04-04 09:06 UTC, TechQuery requested changes

2021-04-04 09:06 UTC, TechQuery commented on script/toMarkdown/index.js
> +    fsPromises.writeFile(Path_ArticleFolder_R + articleFileName, articleText);
此处 `await` 才能被 `try {} catch {}` 处理

2021-04-04 09:06 UTC, TechQuery commented on script/toMarkdown/toMarkdownSubfun.js
>        // console.log(URLArr);
测试用的 `console.log()` 都删掉

2021-04-04 09:06 UTC, TechQuery commented on script/toMarkdown/toMarkdownSubfun.js
> +    turndownService
中间件引用也放到上面一起初始化，否则会反复执行

2021-04-04 15:15 UTC, TechQuery commented on .github/workflows/WebPageToMarkdown.yml
> +                  fi;
@stevending1st 这里咋又退回来了呢？

2021-04-05 08:25 UTC, TechQuery approved these changes

2021-04-05 09:46 UTC, merged