The definitive node js handbook
freeCodeCamp/news-translation pull request #619
Opened 2022-02-20 11:46 UTC by luojiyin1987

Checklist:

- [ ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ ] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #XXXXX

2022-02-20 11:47 UTC, luojiyin1987 commented
#618

2022-02-28 02:58 UTC, luojiyin1987 commented
@miyaliu666     已经完成翻译。  原作者写的不是很严格，我已经调整了很多。 现在还是存在格式上的问题。 示范代码，更多是示意，不一定能跑起来。

2022-04-12 08:18 UTC, miyaliu666 commented
@TechQuery 水歌有时间帮忙检查一下这篇译文吗？谢谢！

2022-04-12 15:49 UTC, TechQuery requested changes
不要改文件名，否则 reviewer 没法看到差异对比……

2022-04-13 09:31 UTC, luojiyin1987 commented
![image](https://user-images.githubusercontent.com/6524977/163146133-eeb4b089-a372-41df-908d-9f51716c9d7c.png)
能看到文件差异对比

2022-04-13 15:35 UTC, TechQuery requested changes
先全面修正一下类似问题我再接着 review

2022-04-13 15:35 UTC, TechQuery commented on chinese/articles/the-definitive-node-js-handbook.md
> +凭借其简单的结构，node包管理器（[npm][2]）帮助Node.js的生态系统激增。现在，[npm registry][3] 托管了近50万个开源包，你可以自由使用。
专有名词首字母大写，缩写全大写

2022-04-13 15:35 UTC, TechQuery commented on chinese/articles/the-definitive-node-js-handbook.md
>  const hostname = '127.0.0.1'const port = 3000
第二个 `const` 前面要换行

2022-04-13 15:35 UTC, TechQuery commented on chinese/articles/the-definitive-node-js-handbook.md
>  ```
这一段应在同一代码块

2022-04-13 15:35 UTC, TechQuery commented on chinese/articles/the-definitive-node-js-handbook.md
>  const server = http.createServer((req, res) => {  res.statusCode = 200  res.setHeader('Content-Type', 'text/plain')  res.end('Hello World\n')})
左花括号后、右花括号前应有换行

2022-04-13 15:35 UTC, TechQuery commented on chinese/articles/the-definitive-node-js-handbook.md
>  const args = process.argv.slice(2)args[0]
`args[0]` 前有换行

2022-04-13 15:35 UTC, TechQuery commented on chinese/articles/the-definitive-node-js-handbook.md
> +const timer = setInterval(() => {bar.tick() if(bar.complete) {clearInterval(timer)}}, 100)
同一代码块、换行

2022-04-13 15:35 UTC, TechQuery commented on chinese/articles/the-definitive-node-js-handbook.md
>  ```
同一代码块、换行

2022-04-13 15:35 UTC, TechQuery commented on chinese/articles/the-definitive-node-js-handbook.md
>  ```
同一代码块、换行

2022-04-13 19:08 UTC, TechQuery commented on chinese/articles/the-definitive-node-js-handbook.md
> +Node.js是一个**的JavaScript运行环境**，运行在**的服务器**上。
语句不通啊

2022-04-14 02:13 UTC, luojiyin1987 commented on chinese/articles/the-definitive-node-js-handbook.md
> +凭借其简单的结构，node包管理器（[npm][2]）帮助Node.js的生态系统激增。现在，[npm registry][3] 托管了近50万个开源包，你可以自由使用。
`npm` 改为  `NPM`,   `node` 改为`Node`。

2022-04-14 02:18 UTC, luojiyin1987 commented on chinese/articles/the-definitive-node-js-handbook.md
>  ```
已经合并代码

2022-04-14 02:31 UTC, luojiyin1987 commented on chinese/articles/the-definitive-node-js-handbook.md
>  const server = http.createServer((req, res) => {  res.statusCode = 200  res.setHeader('Content-Type', 'text/plain')  res.end('Hello World\n')})
已添加换行

2022-04-14 02:38 UTC, luojiyin1987 commented on chinese/articles/the-definitive-node-js-handbook.md
>  ```
已经调整

2022-04-14 02:44 UTC, luojiyin1987 commented on chinese/articles/the-definitive-node-js-handbook.md
>  const chalk = require('chalk')console.log(chalk.yellow('hi!'))
已换行

2022-04-14 02:47 UTC, luojiyin1987 commented on chinese/articles/the-definitive-node-js-handbook.md
> +const timer = setInterval(() => {bar.tick() if(bar.complete) {clearInterval(timer)}}, 100)
已经格式化代码

2022-04-14 02:50 UTC, luojiyin1987 commented on chinese/articles/the-definitive-node-js-handbook.md
>  ```
已经格式化代码

2022-04-14 02:53 UTC, luojiyin1987 commented on chinese/articles/the-definitive-node-js-handbook.md
>  ```
已经调整

2022-04-14 04:50 UTC, luojiyin1987 commented
我吐槽原文的对示范代码，对初学者很不友好。

2022-04-14 14:21 UTC, miyaliu666 commented
辛苦两位了  @luojiyin1987  @TechQuery  现在可以合并了吗？

2022-04-14 15:29 UTC, TechQuery requested changes
再改一下类似问题，我再 review 剩下的

2022-04-14 15:29 UTC, TechQuery commented on chinese/articles/the-definitive-node-js-handbook.md
>  app.listen(3000, () => console.log('Server ready'))
同一代码块

2022-04-14 15:29 UTC, TechQuery commented on chinese/articles/the-definitive-node-js-handbook.md
>  process.argv.forEach((val, index) => {  console.log(`${index}: ${val}`)})
代码换行

2022-04-14 15:29 UTC, TechQuery commented on chinese/articles/the-definitive-node-js-handbook.md
> +at function1 (repl:1:25)    at repl:1:1
at 换行

2022-04-14 15:29 UTC, TechQuery commented on chinese/articles/the-definitive-node-js-handbook.md
> +    if (bar.complete) { clearInterval(timer) }
换行

2022-04-14 15:29 UTC, TechQuery commented on chinese/articles/the-definitive-node-js-handbook.md
> +const readline = require('readline').createInterface({ input: process.stdin, output: process.stdout })
对象字面量内换行

2022-04-14 15:29 UTC, TechQuery commented on chinese/articles/the-definitive-node-js-handbook.md
> +const questions = [{ type: 'input', name: 'name', message: "What's your name?", }]
对象字面量换行

2022-04-14 15:29 UTC, TechQuery commented on chinese/articles/the-definitive-node-js-handbook.md
>  module.exports = car
同一代码块

2022-04-14 15:29 UTC, TechQuery commented on chinese/articles/the-definitive-node-js-handbook.md
>  ```
同一代码块

2022-04-14 15:29 UTC, TechQuery commented on chinese/articles/the-definitive-node-js-handbook.md
>  "name": "test-project"
外层花括号缺失

2022-04-14 15:29 UTC, TechQuery commented on chinese/articles/the-definitive-node-js-handbook.md
>  "license": "MIT"
外层花括号

2022-04-14 15:29 UTC, TechQuery commented on chinese/articles/the-definitive-node-js-handbook.md
>  "keywords": [  "email",  "machine learning",  "ai"]
外层花括号

2022-04-14 15:29 UTC, TechQuery commented on chinese/articles/the-definitive-node-js-handbook.md
>  "description": "A package to work with strings"
外层花括号

2022-04-14 15:29 UTC, TechQuery commented on chinese/articles/the-definitive-node-js-handbook.md
>  ```
外层花括号

2022-04-14 15:29 UTC, TechQuery commented on chinese/articles/the-definitive-node-js-handbook.md
>  ❯ npm list/Users/flavio/dev/node/cowsay└─┬ cowsay@1.3.1  ├── get-stdin@5.0.1  ├─┬ optimist@0.6.1  │ ├── minimist@0.0.10  │ └── wordwrap@0.0.3  ├─┬ string-width@2.1.1  │ ├── is-fullwidth-code-point@2.
树状结构换行（下同）

2022-04-14 15:29 UTC, TechQuery commented on chinese/articles/the-definitive-node-js-handbook.md
>  {  "requires": true,  "lockfileVersion": 1,  "dependencies": {    "cowsay": {      "version": "1.3.1",      "resolved": "https://registry.npmjs.org/cowsay/-/cowsay-1.3.1.tgz",      "integrity": "sha5
换行

2022-04-14 15:29 UTC, TechQuery commented on chinese/articles/the-definitive-node-js-handbook.md
> +- `||`: 你结合一组。例如: `< 2.1 || &g`t; 2.6
`&gt;` 替换为 `>`，`&lt;` 则为 `<`

2022-04-14 15:29 UTC, TechQuery commented on chinese/articles/the-definitive-node-js-handbook.md
> +如果软件包是一个开发依赖，列在`package.json`文件的devDependencies中，你必须使用`-D`/`-save-dev`标志从文件中删除它:
`--save-dev`

2022-04-14 15:29 UTC, TechQuery commented on chinese/articles/the-definitive-node-js-handbook.md
>  _______< Hello > -------        \   ^__^         \  (oo)\_______            (__)\       )\/\                ||----w |                ||     ||
ASCII 图形画换行

2022-04-14 15:29 UTC, TechQuery commented on chinese/articles/the-definitive-node-js-handbook.md
同一代码块

2022-04-14 15:29 UTC, TechQuery commented on chinese/articles/the-definitive-node-js-handbook.md
>  foobarbaz
输出文字换行

2022-04-14 15:29 UTC, TechQuery commented on chinese/articles/the-definitive-node-js-handbook.md
>  ```
同一代码块

2022-04-14 15:29 UTC, TechQuery commented on chinese/articles/the-definitive-node-js-handbook.md
>  ```
同一代码块

2022-04-14 15:29 UTC, TechQuery commented on chinese/articles/the-definitive-node-js-handbook.md
>  ```
同一代码块

2022-04-14 15:29 UTC, TechQuery commented on chinese/articles/the-definitive-node-js-handbook.md
>  ```
同一代码块

2022-04-15 11:00 UTC, TechQuery requested changes
第三次 review 还有大量前两次中的同类问题，请先通篇复查、修改。

2022-04-16 08:50 UTC, luojiyin1987 commented
@TechQuery   
```js
const bar = () => console.log('bar')

const baz = () => console.log('baz')
process.nextTick(() => {todo})//do something
```
这种简短的代码，我倾向不换行。

@miyaliu666   怎样让英文的原作者，也改改他的文章。

2022-04-16 10:44 UTC, TechQuery commented
> ```js
> const bar = () => console.log('bar')
> 
> const baz = () => console.log('baz')
> process.nextTick(() => {todo})//do something
> ```
> 
> 这种简短的代码，我倾向不换行。

你这么写的话，`todo` 是个标识符，但代码上下文中没有，新人直接复制粘贴会报错，误人子弟。

原文用的**单行注释**，一定是独立成行的，可能是这个仓库的爬虫程序给弄没了，翻译时需要照原文修复。

2022-04-16 11:17 UTC, TechQuery commented
@luojiyin1987 你可以改一批一次性提交，一点一提交量太大，GitHub 也卡。

2022-04-16 12:06 UTC, luojiyin1987 commented
@TechQuery    todo 倾向改改成什么类型 ？

2022-04-16 13:03 UTC, luojiyin1987 commented
@TechQuery    
```js
你这么写的话，todo 是个标识符，但代码上下文中没有，新人直接复制粘贴会报错，误人子弟。
```
原来的代码
```js
process.nextTick(() => {  //do something})
```

2022-04-16 13:27 UTC, luojiyin1987 commented
@TechQuery    todo  改成 Node 官网提供的例子， 或者实际能运行的代码。

2022-04-16 15:47 UTC, luojiyin1987 commented
我 git brebase ， 删除大部分提交记录。

2022-04-16 17:35 UTC, TechQuery commented
@luojiyin1987 

> 原文用的**单行注释**，一定是独立成行的，可能是这个仓库的爬虫程序给弄没了，翻译时需要照原文修复。

你在原文代码中的单行注释前后加换行符就行了，无需自己改写。

2022-04-16 18:03 UTC, TechQuery requested changes

2022-04-16 18:03 UTC, TechQuery commented on chinese/articles/the-definitive-node-js-handbook.md
>  ee.once('my-event', () => {  //call callback function once})
注释换行

2022-04-16 18:03 UTC, TechQuery commented on chinese/articles/the-definitive-node-js-handbook.md
>  > require('http').METHODS[ 'ACL',  'BIND',  'CHECKOUT',  'CONNECT',  'COPY',  'DELETE',  'GET',  'HEAD',  'LINK',  'LOCK',  'M-SEARCH',  'MERGE',  'MKACTIVITY',  'MKCALENDAR',  'MKCOL',  'MOVE',  'NO
`[` 前换行

2022-04-16 18:03 UTC, TechQuery commented on chinese/articles/the-definitive-node-js-handbook.md
>  > require('http').STATUS_CODES{ '100': 'Continue',  '101': 'Switching Protocols',  '102': 'Processing',  '200': 'OK',  '201': 'Created',  '202': 'Accepted',  '203': 'Non-Authoritative Information',
`{` 前换行

2022-04-16 18:03 UTC, TechQuery commented on chinese/articles/the-definitive-node-js-handbook.md
> +const options = {  user: 'the_mysql_user_name',  password: 'the_mysql_user_password',  database: 'the_mysql_database_name'}
花括号内键值对换行

2022-04-16 18:03 UTC, TechQuery commented on chinese/articles/the-definitive-node-js-handbook.md
>  const options = {  user: 'the_mysql_user_name',  password: 'the_mysql_user_password',  database: 'the_mysql_database_name'}
花括号内键值对换行

2022-04-17 07:32 UTC, TechQuery commented on chinese/articles/the-definitive-node-js-handbook.md
>  ```
这里你直接复制我的代码，粘贴到你的 markdown 文件即可：
![image](https://user-images.githubusercontent.com/19969570/163705153-af784787-516f-4e42-a12c-3a3372924722.png)

2022-04-17 08:08 UTC, luojiyin1987 commented
@TechQuery   已经修改有关  Node REPL 的markdown

2022-04-17 10:55 UTC, TechQuery approved these changes

2022-04-17 10:56 UTC, merged

2022-04-17 11:57 UTC, luojiyin1987 commented
@miyaliu666   @TechQuery   辛苦了。