javascript-under-the-hood-v8
freeCodeCamp/news-translation pull request #715
Opened 2022-04-21 03:33 UTC by luojiyin1987

Checklist:

- [ ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ ] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #248

2022-04-22 08:33 UTC, luojiyin1987 commented
翻译中的  `Shape`    在不同js 引擎中有不同的别名。 我就保留这个词，不翻译了

2022-04-22 09:02 UTC, miyaliu666 commented on chinese/articles/javascript-under-the-hood-v8.md
> +[解析器][11] 捡起它并创建一个 [抽象语法树（AST）][12]：源代码的树状表示。树上的每个节点都表示代码中出现的一个结构。
捡起来 => 识别

2022-04-22 09:14 UTC, miyaliu666 commented on chinese/articles/javascript-under-the-hood-v8.md
> +你可以想象，在一个大的网络应用中，你会看到大量的  shapes。同时，在链接列表中搜索需要线性时间，使得属性查找成为一个非常昂贵的操作。
一个非常耗费时间的操作

2022-04-22 09:15 UTC, miyaliu666 commented on chinese/articles/javascript-under-the-hood-v8.md
> +**注意：你可以记住这一点，但如果导致代码重复或代码表现力降低，就不要这样做。**
性能降低

2022-04-22 12:18 UTC, TechQuery requested changes
你先改这些，我后面慢慢审核。

2022-04-22 12:18 UTC, TechQuery commented on chinese/articles/javascript-under-the-hood-v8.md
> +V8需要做的第一件事是下载源代码。这可以通过网络、缓存或 service workers 来完成。
很短的句子都用中文逗号来断句，因为往往后面的句子是一个代词开头，指代的主语在前半句。（下同）

2022-04-22 12:18 UTC, TechQuery commented on chinese/articles/javascript-under-the-hood-v8.md
> +你还会看到 `VariableProxy`--一个将抽象变量连接到内存中某个地方的元素。解决 `VariableProxy` 的过程被称为 **范围分析(Scope Analysis)**。
破折号、作用域分析

2022-04-22 12:18 UTC, TechQuery commented on chinese/articles/javascript-under-the-hood-v8.md
> +## The Just-in-Time (JIT) paradigm（即时编译）
“范例”不翻译？

2022-04-26 19:44 UTC, TechQuery requested changes

2022-04-26 19:44 UTC, TechQuery commented on chinese/articles/javascript-under-the-hood-v8.md
> +你可以查看 [在相应的源代码中][14] 所有可用的字节码。如果你对其他 JS 概念（如循环和async/await）如何在字节码中呈现感兴趣，我觉得通过这些 [测试用例][15]来阅读是很有用的。
> 你可以[在相应的源代码中][14]查看

2022-04-26 19:44 UTC, TechQuery commented on chinese/articles/javascript-under-the-hood-v8.md
> +生成后，Ignition 将使用一个以字节码为关键的处理程序表来解释这些指令。对于每个字节码，Ignition 可以查找相应的处理程序函数，并使用提供的参数执行它们。
1. “生成结束后”
2. “以字节码为索引”

2022-04-26 19:44 UTC, TechQuery commented on chinese/articles/javascript-under-the-hood-v8.md
> +为了解决这个问题，V8 使用 **Object Shapes**（或内部映射 Maps internally）和内存中的值向量将对象的结构与值本身分开。
“对象形状”也注明一下

2022-04-26 19:44 UTC, TechQuery commented on chinese/articles/javascript-under-the-hood-v8.md
> +例如，我们创建一个对象字面:
对象字面量

2022-04-26 19:44 UTC, TechQuery commented on chinese/articles/javascript-under-the-hood-v8.md
> +Object shapes 本质上是链接列表。因此，如果你写 `c.x`，V8 会去到列表的头部，在那里找到 `y`，移动到连接的 shape，最后它得到 `x` 并从中读取偏移。然后它将进入内存向量并返回其中的第一个元素。
“链接列表” => “链表”

2022-04-26 19:44 UTC, TechQuery commented on chinese/articles/javascript-under-the-hood-v8.md
> +你可以想象，在一个大的网络应用中，你会看到大量的  shapes。同时，在链接列表中搜索需要线性时间，使得属性查找成为一个非常昂贵的操作，非常消耗时间。
> 使得属性查找成为一个非常耗时的操作。

2022-04-26 19:44 UTC, TechQuery commented on chinese/articles/javascript-under-the-hood-v8.md
> +为了解决V8中的这个问题，你可以使用 [**在线缓存 Inline Cache（IC）**][16]。它记住了在哪里可以找到对象的属性的信息，以减少查找的次数。
“内联缓存”

2022-04-26 19:44 UTC, TechQuery commented on chinese/articles/javascript-under-the-hood-v8.md
> +**注意：你可以记住这一点，但如果导致代码重复或代码性能降低，就不要这样做。**
“代码可读性降低”

2022-04-26 19:44 UTC, TechQuery commented on chinese/articles/javascript-under-the-hood-v8.md
> +内联缓存还可以跟踪它们被调用的频率，以决定它是否是优化编译器的好候选者--Turbofan。
破折号

2022-04-26 19:44 UTC, TechQuery commented on chinese/articles/javascript-under-the-hood-v8.md
> +Ignition只能让我们走到这里。如果一个函数变得足够热(译者注： 调用频繁)，它将在编译器中被优化，[Turbofan][18]，以使其更快。
中文圆括号

2022-04-26 19:44 UTC, TechQuery commented on chinese/articles/javascript-under-the-hood-v8.md
> +Turbofan 从 Ignition 中获取字节码和函数的类型反馈（Feedback Vector），在此基础上应用一系列的缩减，并产生机器码。
“一系列的浓缩处理”

2022-04-26 19:44 UTC, TechQuery commented on chinese/articles/javascript-under-the-hood-v8.md
> +4. 在这一点上，引擎开始运行代码并收集类型反馈。
> 4. 此时，

2022-04-26 19:44 UTC, TechQuery commented on chinese/articles/javascript-under-the-hood-v8.md
> +这就是了! 如果你对上面某个特定的阶段有任何疑问，或者想了解更多的细节，你可以潜心研究源代码，或者在 [Twitter][19] 上联系我。
> 就是这样！

2022-04-26 19:44 UTC, TechQuery commented on chinese/articles/javascript-under-the-hood-v8.md
> +- [life of a script][20] 来自谷歌的视频
原文题目的拼写要留着

2022-04-26 19:44 UTC, TechQuery commented on chinese/articles/javascript-under-the-hood-v8.md
> +- [A crash course in JIT compilers][21] 来自Mozilla
“来自 XX 的 YY”

2022-04-27 16:15 UTC, TechQuery approved these changes

2022-04-27 16:15 UTC, merged